pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success= nix flake check
      - check-success= nix fmt
      - check-success= build home-manager common
      - check-success= nixos test minimal
      - check-success= nixos test common
      - check-success= nixos test neovim
      - title= "flake.lock: Update"
      - or:
        - author=a-kenji
        - author=github-actions[bot]
    actions:
      merge:
        method: merge
      delete_head_branch: {}
