pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=home-manager
      - check-success=nix
      - check-success=nixos
      - or:
        - author=a-kenji
        - author=github-actions[bot]
    actions:
      merge:
        method: merge
      delete_head_branch: {}
