pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=home-manager/common
      - check-success=nix:check
      - check-success=nix:fmt
      - check-success=nixos:nixos-test
      - check-success=nixos:common-test
      - check-success=nixos:neovim-test
      - or:
        - author=a-kenji
        - author=github-actions[bot]
    actions:
      merge:
        method: merge
      delete_head_branch: {}
