reporting: "off"
update:
  method: never
gui:
  showFileTree: true
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --syntax-theme "Dracula" --paging=never
customCommands:
  - key: '<c-r>'
    command: 'git rebase --interactive "{{.SelectedLocalCommit.Sha}}"'
    context: 'commits'
    subprocess: true
  - key: '<c-n>'
    prompts:
      - type: 'input'
        title: 'What is the new branch name?'
        initialValue: ''
    command: 'git fetch upstream master && git branch --merged upstream/master | xargs --no-run-if-empty git branch -D && git checkout -b "{{index .PromptResponses 0}}" upstream/master && git cherry-pick "{{.SelectedLocalCommit.Sha}}" && git push -u origin {{index .PromptResponses 0}}'
    context: 'commits'
    subprocess: true
  - key: '<c-a>'
    context: "global"
    command: 'for b in upstream/main upstream/master origin/main origin/master; do if git rev-parse --verify $b; then git absorb --and-rebase --base $b; break; fi; done'
    subprocess: true
