name: "home-manager"
on:
  pull_request:
  push:
jobs:
  nix-build-home:
    runs-on: ubuntu-latest
    name: "common"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#hmConfigurations.common.activationPackage
