name: "home-manager"
on:
  push:
    branches: [main]
  pull_request:
  # Called by pull-request when specifically requested
  workflow_call:
jobs:
  nix-build-minimal:
    runs-on: ubuntu-latest
    name: "build home-manager minimal"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -Lv .#legacyPackages."x86_64-linux".home-manager.minimal.activationPackage

  nix-build-neovim:
    runs-on: ubuntu-latest
    name: "build home-manager neovim"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -Lv .#legacyPackages."x86_64-linux".home-manager.neovim.activationPackage

  nix-build-tools:
    runs-on: ubuntu-latest
    name: "build home-manager tools"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -Lv .#legacyPackages."x86_64-linux".home-manager.tools.activationPackage

  nix-build-common:
    runs-on: ubuntu-latest
    name: "build home-manager common"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -Lv .#legacyPackages."x86_64-linux".home-manager.common.activationPackage
