name: "nix"
on:
  push:
    branches: [main]
  pull_request:
  # Called by pull-request when specifically requested
  workflow_call:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    name: "nix flake check"
    environment: cachix
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
  nixfmt:
    runs-on: ubuntu-latest
    name: "nix fmt"
    environment: cachix
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "treefmt"
      run: nix develop .#fmtShell --command treefmt --fail-on-change

  lint:
    runs-on: ubuntu-latest
    name: "lint actions"
    environment: cachix
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "actionlint"
      run: nix develop .#fmtShell --command actionlint
