name: "nix"
on:
  pull_request:
  push:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    name: "nix flake check"
    environment: cachix
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
  nixfmt:
    runs-on: ubuntu-latest
    name: "nix fmt"
    environment: cachix
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/cachix-action@v10
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "treefmt"
      run: nix develop .#fmtShell --command treefmt --fail-on-change
