name: "nixos"
on:
  pull_request:
  push:
jobs:
  build-nixos:
    runs-on: ubuntu-latest
    name: "common-test"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.common-test.config.system.build.toplevel
  nixos-tests:
    runs-on: ubuntu-latest
    name: "nixos-test"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
    - run: nix build .#nixosModules.tests.minimal
  neovim-test:
    runs-on: ubuntu-latest
    name: "neovim-test"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build .#nixosModules.tests.neovim --impure
