name: "nixos"
on:
  pull_request:
  push:
jobs:
  build-nixos:
    runs-on: ubuntu-latest
    name: "common-test"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.common-test.config.system.build.toplevel
    - run: nix build .#nixosModules.tests.minimal
