name: "nixos"
on:
  push:
    branches: [main]
  pull_request:
  # Called by pull-request when specifically requested
  workflow_call:
jobs:
  build-nixos:
    runs-on: ubuntu-latest
    name: "nixos test common"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          "system-features = nixos-test benchmark big-parallel kvm"
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#nixosConfigurations.common-test.config.system.build.toplevel
  nixos-tests:
    runs-on: ubuntu-latest
    name: "nixos test minimal"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#nixosModules.tests.minimal
  neovim-test:
    runs-on: ubuntu-latest
    name: "nixos test neovim"
    environment: "cachix"
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: kenji
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#nixosModules.tests.neovim
